# Generated by Django 5.0.6 on 2024-06-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodels',
            name='age_limit',
            field=models.IntegerField(),
        ),
    ]
