# Generated by Django 5.0.6 on 2024-06-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_alter_videomodels_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodels',
            name='age_limit',
            field=models.CharField(default='00', max_length=2),
        ),
    ]
